name: Train on EPIC-KITCHENS subset

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows you to start manually

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision torchaudio numpy opencv-python

    - name: Download small EPIC-KITCHENS subset
      run: |
        python epic_downloader.py --videos --participants P01 --output-path ./data

    - name: Train CNN-LSTM model
      run: |
        python train_cnn_lstm.py --data ./data --epochs 3
        mkdir -p models
        mv cnn_lstm_model.pt models/

    - name: Train 3D CNN model
      run: |
        python train_3dcnn.py --data ./data --epochs 3
        mv cnn3d_model.pt models/

    - name: Upload trained models
      uses: actions/upload-artifact@v4
      with:
        name: trained_models
        path: models/
